### ISSUE TITLE
Outline adjustment

### ISSUE THREAD

**Issue by krwu** [spiral/docs#128]
I'm a little confused to current documents' outline:

It seems that the section "Getting Started" is mainly introductions to the framework and some related strategies(versioning, contributing...), but there is an "action guide" mixed into it: installing.

In my opinion, installing should be a part of "how to make the project running", including "installing, configuration, trying it out, deployment". That is what "getting started" or "quick start" should do.

I think this should be better:

- Overview
  - About Spiral
  - Versioning
  - Changelog
  - Contributing
  - LICENSE
- Getting Started
  - Installing
  - Directory Structure
  - Configuration
  - Trying it
  - Deployment
- Basics
...

"Cookbook" and "Basics" are both "basic knowledge" to use this framework to develop applications. I suggest that "Basics" should be some "more basic" things for a simple web application, like "Routing, Controller, Views, Database, ORM, Handler, Security, Testing..." "Cookbook" is deeper, like "Console,  Queue, Jobs, Internalization,  Event Broadcasting, GRPC..."

There could be another section "Components", all official components' documents can be put there.

**Comment by wolfy-j** [comment]
That's a deep insight... and I agree, the proposed approach looks logical to me. I'll accept PRs related to such changes and will work on better structure after finishing the rest of the remaining articles. 

Thank you for the proposal!

**Comment by krwu** [comment]
I agree.

We should do this after the remaining articles finished.
