### ISSUE TITLE
Does "queue" here should be "Cookie"?

### ISSUE THREAD

**Issue by krwu** [spiral/docs#158]
In [Usage with Singletons](https://spiral.dev/docs/http-cookies#usage-with-singletons) section, the paragraph:

> You can not use `CookieQuery` as `__construct` argument. **Queue** is only available within IoC context of CookieMiddleware and must be requested from container directly (use use method injection as showed above):

Does "Queue" here should be "Cookie"?

**Comment by wolfy-j** [comment]
Yes, it should be `CookieQueue`

**Comment by krwu** [comment]
> Yes, it should be `CookieQueue`

Got it, thanks!
