### ISSUE TITLE
Feature request to update docs: Building Application Server

### ISSUE THREAD

**Issue by connerbw** [spiral/docs#176]
Had some fun today with the framework. Really cool. However I hit a snag when I followed this step:

> Create main.go: Download default main.go file, we are going to use it later to register custom services. You can store this file in the root of your project or other location.

Source: https://spiral.dev/docs/framework-application-server

My issues:
 + Storing  file in the root of the project broke `vendor/` directory. (Composer and Go mod both try to use `vendor/`)
 + Compile errors. (`github.com/spiral/broadcast` was being downloaded as v1 instead of v2+ gave weird "not found" errors)

Workaround(s):

+ Create a separate sub-folder just for go. I used `golang/`. (I also put [my RPC code](https://spiral.dev/docs/cookbook-golang-library) in there.)
+ Download both `main.go` and `go.mod`

Next, in `go.mod`:
 + Change `module github.com/spiral/framework` to `module <your-github-skeleton-repo>`
 + Change the go version to your own

Next, to get everything working I did:

```
cd golang
go build
mv <your-github-skeleton-repo> ../spiral
cd ..
spiral -v -d
```

Thanks!

**Comment by wolfy-j** [comment]
Thank you for the proposal.

@SerafimArts can you help to aknowledge this issue?

**Comment by connerbw** [comment]
I started with  `composer create-project spiral/app` and I think some of my difficulties arise from the PHP vendor directory including a lot of `.go` files. I wrote a blog howto/tutorial about how to compile a custom Roadrunner server, start developing with Spiral, using Docker that explains how I got things working. It's for newbies, but maybe some of these ideas could make their way into the official docs. Here's the link:

https://kizu514.com/blog/php-and-go-together-at-last/

**Comment by SerafimArts** [comment]
@wolfy-j no, I cant.

**Comment by wolfy-j** [comment]
I'll handle it next week then.

**Comment by butschster** [comment]
You can find information here https://roadrunner.dev/docs/app-server-build/2.x/en
