### ISSUE TITLE
How good guide / documentation should looks like?

### ISSUE THREAD

**Issue by wolfy-j** [spiral/docs#89]
Does anyone has good example? What should be covered in guide first?

**Comment by vvval** [comment]
If talking about readme.md, then first of all users need to see easy example of usage, I think it isn't important to show ALL available features but the least and necessary amount of them. Configs - mention only database config, 1-3 dark templates, 1 controller, source, service and entity model

**Comment by wolfy-j** [comment]
So basically use skeleton app as reference? Probably i should describe it in docs as well.

**Comment by wolfy-j** [comment]
Thx
